from django.contrib import admin

# Register your models here.
from RSR.models import *
admin.site.register(Document)
admin.site.register(Person)
admin.site.register(Major)
admin.site.register(School)
admin.site.register(Coursework)
admin.site.register(ProfessionalDevelopment)
admin.site.register(SideProject)
admin.site.register(Skills)
admin.site.register(LanguageSpoken)
admin.site.register(Clearance)
admin.site.register(Company)
admin.site.register(Awards)
admin.site.register(Clubs_Hobbies)
admin.site.register(Volunteering)
admin.site.register(PersonToCompany)
admin.site.register(PersonToSchool)
admin.site.register(PersonToSkills)
admin.site.register(PersonToAwards)
admin.site.register(PersonToClearance)
admin.site.register(PersonToClubs_Hobbies)
admin.site.register(PersonToCourse)
admin.site.register(PersonToLanguage)
admin.site.register(PersonToProfessionalDevelopment)
admin.site.register(PersonToSide)
admin.site.register(PersonToVolunteering)
