# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y%m%d')),
            ],
        ),
        migrations.CreateModel(
            name='Graduation_Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_month', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Graduation_Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField(default=1900)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('major',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('language', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=500)),
                ('certificate', models.CharField(max_length=500)),
                ('awards', models.CharField(max_length=500)),
                ('professional_development', models.CharField(max_length=500)),
                ('prior_company', models.CharField(max_length=100)),
                ('year_of_experience', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('title', models.CharField(max_length=200)),
                ('graduation_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Graduation_Month')),
                ('graduation_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Graduation_Year')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Major')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('school',),
            },
        ),
        migrations.CreateModel(
            name='School_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_level', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('school_level',),
            },
        ),
        migrations.CreateModel(
            name='Security_Clearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_clearance', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('security_clearance',),
            },
        ),
        migrations.CreateModel(
            name='Work_Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_authorization', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('work_authorization',),
            },
        ),
        migrations.AddField(
            model_name='person',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.School'),
        ),
        migrations.AddField(
            model_name='person',
            name='school_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.School_level'),
        ),
        migrations.AddField(
            model_name='person',
            name='security_clearance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Security_Clearance'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_authorization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Work_Authorization'),
        ),
    ]
