# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=16, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=16, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='persontoschool',
            name='GPA',
            field=models.DecimalField(decimal_places=2, default='None', max_digits=3, max_length=20, verbose_name='GPA'),
        ),
    ]
