# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_company',
            name='EndDate',
            field=models.DateField(default=10, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='person_company',
            name='StartDate',
            field=models.DateField(default=10, verbose_name='Start Date'),
        ),
    ]
