# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('ClearanceLevel', models.CharField(default='None', max_length=30, primary_key=True, serialize=False, verbose_name='Clearance Level')),
            ],
        ),
        migrations.CreateModel(
            name='PersonToClearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClearanceLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Clearance')),
            ],
        ),
        migrations.CreateModel(
            name='PersonToProfessionalDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(default='None', max_length=30, verbose_name='Professional Development Description')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='None', max_length=20, verbose_name='Professional Development')),
            ],
        ),
        migrations.RemoveField(
            model_name='persontocertificate',
            name='CertID',
        ),
        migrations.RemoveField(
            model_name='persontocertificate',
            name='PersonID',
        ),
        migrations.RemoveField(
            model_name='persontoclearence',
            name='ClearenceLevel',
        ),
        migrations.RemoveField(
            model_name='persontoclearence',
            name='PersonID',
        ),
        migrations.RenameField(
            model_name='persontoawards',
            old_name='AwardName',
            new_name='AwardID',
        ),
        migrations.RenameField(
            model_name='persontoclubs_hobbies',
            old_name='CHName',
            new_name='CHID',
        ),
        migrations.RenameField(
            model_name='persontocompany',
            old_name='CompanyName',
            new_name='CompanyID',
        ),
        migrations.RenameField(
            model_name='persontovolunteering',
            old_name='VolunName',
            new_name='VolunID',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='AwardDescriptioin',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='AwardName',
        ),
        migrations.RemoveField(
            model_name='clubs_hobbies',
            name='CHDesc',
        ),
        migrations.RemoveField(
            model_name='clubs_hobbies',
            name='CHName',
        ),
        migrations.RemoveField(
            model_name='company',
            name='CompanyName',
        ),
        migrations.RemoveField(
            model_name='coursework',
            name='Desc',
        ),
        migrations.RemoveField(
            model_name='sideproject',
            name='ProjectDesc',
        ),
        migrations.RemoveField(
            model_name='sideproject',
            name='ProjectName',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='SkillsName',
        ),
        migrations.RemoveField(
            model_name='volunteering',
            name='VolunDesc',
        ),
        migrations.RemoveField(
            model_name='volunteering',
            name='VolunName',
        ),
        migrations.AddField(
            model_name='awards',
            name='Name',
            field=models.CharField(default='None', max_length=100, verbose_name='Award Name'),
        ),
        migrations.AddField(
            model_name='clubs_hobbies',
            name='Name',
            field=models.CharField(default='None', max_length=100, verbose_name='Club and Hobby Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='Name',
            field=models.CharField(default='None', max_length=100, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='persontoawards',
            name='Desc',
            field=models.CharField(default='None', max_length=1000, verbose_name='Award Description'),
        ),
        migrations.AddField(
            model_name='persontoclubs_hobbies',
            name='Desc',
            field=models.CharField(default='None', max_length=100, verbose_name='Club and Hobby Description'),
        ),
        migrations.AddField(
            model_name='persontocompany',
            name='Desc',
            field=models.CharField(default='None', max_length=1000, verbose_name='Company Description'),
        ),
        migrations.AddField(
            model_name='persontocourse',
            name='Desc',
            field=models.CharField(default='None', max_length=50, verbose_name='Coursework Description'),
        ),
        migrations.AddField(
            model_name='persontoside',
            name='Desc',
            field=models.CharField(default='None', max_length=50, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='persontovolunteering',
            name='Desc',
            field=models.CharField(default='None', max_length=1000, verbose_name='Volunteering Description'),
        ),
        migrations.AddField(
            model_name='sideproject',
            name='Name',
            field=models.CharField(default='None', max_length=20, verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='skills',
            name='Name',
            field=models.CharField(default='None', max_length=20, verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='volunteering',
            name='Name',
            field=models.CharField(default='None', max_length=100, verbose_name='Volunteering Name'),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='Coursework'),
        ),
        migrations.AlterField(
            model_name='languagespoken',
            name='Language',
            field=models.CharField(default='None', max_length=20, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='major',
            name='Dept',
            field=models.CharField(default='None', max_length=50, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='major',
            name='MajorMinor',
            field=models.CharField(default='None', max_length=50, verbose_name='Major/Minor'),
        ),
        migrations.AlterField(
            model_name='major',
            name='Name',
            field=models.CharField(default='None', max_length=50, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Address',
            field=models.CharField(default='None', max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Email',
            field=models.CharField(default='None', max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Name',
            field=models.CharField(default='None', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='PhoneNumber',
            field=models.CharField(default='None', max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='State',
            field=models.CharField(default='None', max_length=25, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ZipCode',
            field=models.IntegerField(default='None', verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=18, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='ExperienceOnJob',
            field=models.CharField(default='None', max_length=300, verbose_name='Experience on Job'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=18, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='Title',
            field=models.CharField(default='None', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='persontocourse',
            name='CourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Coursework'),
        ),
        migrations.AlterField(
            model_name='persontocourse',
            name='PersonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Person'),
        ),
        migrations.AlterField(
            model_name='persontolanguage',
            name='LangID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.LanguageSpoken'),
        ),
        migrations.AlterField(
            model_name='persontolanguage',
            name='PersonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Person'),
        ),
        migrations.AlterField(
            model_name='persontoschool',
            name='CourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Coursework'),
        ),
        migrations.AlterField(
            model_name='persontoschool',
            name='GPA',
            field=models.FloatField(default='None', max_length=20, verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='persontoschool',
            name='GradDate',
            field=models.CharField(default='None', max_length=20, verbose_name='Graduation Date'),
        ),
        migrations.AlterField(
            model_name='persontoschool',
            name='MajorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Major'),
        ),
        migrations.AlterField(
            model_name='persontoschool',
            name='PersonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Person'),
        ),
        migrations.AlterField(
            model_name='persontoschool',
            name='SchoolID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.School'),
        ),
        migrations.AlterField(
            model_name='persontoside',
            name='PersonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Person'),
        ),
        migrations.AlterField(
            model_name='persontoside',
            name='SideID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.SideProject'),
        ),
        migrations.AlterField(
            model_name='persontoskills',
            name='PersonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Person'),
        ),
        migrations.AlterField(
            model_name='persontoskills',
            name='SkillsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Skills'),
        ),
        migrations.AlterField(
            model_name='persontoskills',
            name='YearsOfExperience',
            field=models.CharField(max_length=3, verbose_name='Years Of Experience'),
        ),
        migrations.AlterField(
            model_name='school',
            name='DegreeLevel',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], default='Undergraduate', max_length=50, verbose_name='Degree Level'),
        ),
        migrations.AlterField(
            model_name='school',
            name='Name',
            field=models.CharField(default='None', max_length=50, verbose_name='School'),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Clearence',
        ),
        migrations.DeleteModel(
            name='PersonToCertificate',
        ),
        migrations.DeleteModel(
            name='PersonToClearence',
        ),
        migrations.AddField(
            model_name='professionaldevelopment',
            name='ProfessionalExperience',
            field=models.ManyToManyField(through='RSR.PersonToProfessionalDevelopment', to='RSR.Person'),
        ),
        migrations.AddField(
            model_name='persontoprofessionaldevelopment',
            name='PersonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Person'),
        ),
        migrations.AddField(
            model_name='persontoprofessionaldevelopment',
            name='ProfID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.ProfessionalDevelopment'),
        ),
        migrations.AddField(
            model_name='persontoclearance',
            name='PersonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Person'),
        ),
    ]
