# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0002_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='conference',
            new_name='professional_development',
        ),
    ]
