# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0002_auto_20170710_0105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person_Awards',
            new_name='PersonToAwards',
        ),
        migrations.RenameModel(
            old_name='Person_Certificate',
            new_name='PersonToCertificate',
        ),
        migrations.RenameModel(
            old_name='Person_Clearence',
            new_name='PersonToClearence',
        ),
        migrations.RenameModel(
            old_name='Person_Clubs_Hobbies',
            new_name='PersonToClubs_Hobbies',
        ),
        migrations.RenameModel(
            old_name='Person_Company',
            new_name='PersonToCompany',
        ),
        migrations.RenameModel(
            old_name='Person_Course',
            new_name='PersonToCourse',
        ),
        migrations.RenameModel(
            old_name='Person_Language',
            new_name='PersonToLanguage',
        ),
        migrations.RenameModel(
            old_name='Person_School',
            new_name='PersonToSchool',
        ),
        migrations.RenameModel(
            old_name='Person_Side',
            new_name='PersonToSide',
        ),
        migrations.RenameModel(
            old_name='Person_Skills',
            new_name='PersonToSkills',
        ),
        migrations.RenameModel(
            old_name='Person_Volunteering',
            new_name='PersonToVolunteering',
        ),
    ]
