# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0002_remove_person_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='GitHub',
            field=models.CharField(default='None', max_length=70, verbose_name='GitHub'),
        ),
    ]
