# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0002_auto_20170716_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontoschool',
            name='GPA',
            field=models.DecimalField(decimal_places=1, default='None', max_digits=2, max_length=20, verbose_name='GPA'),
        ),
    ]
