# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0002_auto_20170620_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='awards',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='certificate',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='conference',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.CharField(max_length=500),
        ),
    ]
