# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0002_auto_20170718_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='TypeResume',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Intern', 'Intern'), ('Prospective Employee', 'Prospective Employee'), ('Prospective Intern', 'Prospective Intern')], default='Current Employee', max_length=50, verbose_name='Resume Type'),
        ),
    ]
