# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0003_auto_20170718_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaduser',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=19, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=19, verbose_name='Start Date'),
        ),
    ]
