# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0003_auto_20170710_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontoclubs_hobbies',
            name='CHName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persontoclubshobbies_set', to='RSR.Clubs_Hobbies'),
        ),
        migrations.AlterField(
            model_name='persontoclubs_hobbies',
            name='PersonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persontoclubshobbies_set', to='RSR.Person'),
        ),
    ]
