# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0003_auto_20170716_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontoschool',
            name='GPA',
            field=models.FloatField(default='None', max_length=20, verbose_name='GPA'),
        ),
    ]
