# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0003_auto_20170706_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='wordstr',
            field=models.TextField(),
        ),
    ]
