# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0003_person_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='CreatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='Linkden',
            field=models.CharField(default='None', max_length=70, verbose_name='Linkden'),
        ),
    ]
