# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0004_auto_20170628_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduation_Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_month', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Graduation_Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField(default=1900)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='School_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Security_Clearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_clearance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_authorization', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='graduation_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Graduation_Month'),
        ),
        migrations.AlterField(
            model_name='person',
            name='graduation_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Graduation_Year'),
        ),
        migrations.AlterField(
            model_name='person',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Major'),
        ),
        migrations.AlterField(
            model_name='person',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.School'),
        ),
        migrations.AlterField(
            model_name='person',
            name='school_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.School_level'),
        ),
        migrations.AlterField(
            model_name='person',
            name='security_clearance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Security_Clearance'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_authorization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Work_Authorization'),
        ),
    ]
