# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0004_auto_20170716_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontocompany',
            name='ExperienceOnJob',
            field=models.CharField(default='None', max_length=300, verbose_name='Experience on Job'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='Title',
            field=models.CharField(default='None', max_length=100, verbose_name='Title'),
        ),
    ]
