# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0003_auto_20170706_1917'),
        ('RSR', '0003_auto_20170706_2024'),
        ('RSR', '0004_auto_20170706_1554'),
    ]

    operations = [
    ]
