# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0004_auto_20170707_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Linkden',
        ),
        migrations.AddField(
            model_name='person',
            name='Linkdin',
            field=models.CharField(default='None', max_length=70, verbose_name='Linkdin'),
        ),
    ]
