# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0005_auto_20170711_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Students',
            field=models.ManyToManyField(through='RSR.PersonToSchool', to='RSR.Person'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=12, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=12, verbose_name='Start Date'),
        ),
    ]
