# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0005_auto_20170620_2046'),
        ('RSR', '0002_auto_20170619_2303'),
    ]

    operations = [
    ]
