# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0005_auto_20170720_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='CreationDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=21, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=21, verbose_name='Start Date'),
        ),
    ]
