# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0005_auto_20170716_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaldevelopment',
            name='ProfessionalExperience',
            field=models.ManyToManyField(through='RSR.PersonToProfessionalDevelopment', to='RSR.Person'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=17, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=17, verbose_name='Start Date'),
        ),
    ]
