# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0005_auto_20170629_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation_month',
            name='graduation_month',
            field=models.CharField(max_length=20),
        ),
    ]
