# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0006_merge_20170622_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='graduation_date',
        ),
        migrations.AddField(
            model_name='person',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='person',
            name='graduation_month',
            field=models.IntegerField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='graduation_year',
            field=models.IntegerField(choices=[('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018')], default=1900),
        ),
        migrations.AlterField(
            model_name='person',
            name='awards',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='certificate',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='conference',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='major',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Finance', 'Finance'), ('Information Systems', 'Information Systems'), ('Marketing', 'Marketing'), ('Management', 'Management'), ('Computer Science', 'Computer Science'), ('Supply Chain Mgmt', 'Supply Chain Mgmt')], max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='school',
            field=models.CharField(choices=[('University of Maryland', 'University of Maryland'), ('Ohio State University', 'Ohio State University'), ('Indiana University', 'Indiana University')], max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='school_level',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='security_clearance',
            field=models.CharField(choices=[('Top Secret', 'Top Secret'), ('Secret', 'Secret'), ('Confidential', 'Confidential')], max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_authorization',
            field=models.CharField(choices=[('Citizenship', 'Citizenship'), ('Permanent Resident', 'Permanent Resident'), ('Visa', 'Visa')], max_length=100),
        ),
    ]
