# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0006_auto_20170629_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('school',)},
        ),
    ]
