# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0006_auto_20170721_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='PhoneNumber',
            field=models.CharField(default=0, max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='persontoskills',
            name='YearsOfExperience',
            field=models.CharField(default=1, max_length=3, verbose_name='Years Of Experience'),
        ),
    ]
