# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0006_auto_20170717_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteering',
            name='Volunteer',
            field=models.ManyToManyField(through='RSR.PersonToVolunteering', to='RSR.Person'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=21, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=21, verbose_name='Start Date'),
        ),
    ]
