# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0006_auto_20170712_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonToProfessionalDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonID', models.ForeignKey(db_column='PersonID', on_delete=django.db.models.deletion.DO_NOTHING, to='RSR.Person')),
            ],
        ),
        migrations.RenameModel(
            old_name='Certificate',
            new_name='ProfessionalDevelopment',
        ),
        migrations.RemoveField(
            model_name='persontocertificate',
            name='CertID',
        ),
        migrations.RemoveField(
            model_name='persontocertificate',
            name='PersonID',
        ),
        migrations.DeleteModel(
            name='PersonToCertificate',
        ),
        migrations.AddField(
            model_name='persontoprofessionaldevelopment',
            name='ProfID',
            field=models.ForeignKey(db_column='CertID', on_delete=django.db.models.deletion.DO_NOTHING, to='RSR.ProfessionalDevelopment'),
        ),
    ]
