# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0007_auto_20170711_1945'),
        ('RSR', '0003_auto_20170706_0017'),
    ]

    operations = [
    ]
