# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0007_auto_20170705_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='major',
            options={'ordering': ('major',)},
        ),
        migrations.AlterModelOptions(
            name='security_clearance',
            options={'ordering': ('security_clearance',)},
        ),
        migrations.AlterModelOptions(
            name='work_authorization',
            options={'ordering': ('work_authorization',)},
        ),
    ]
