# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0007_auto_20170712_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=13, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=13, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='persontoprofessionaldevelopment',
            name='ProfID',
            field=models.ForeignKey(db_column='ProfID', on_delete=django.db.models.deletion.DO_NOTHING, to='RSR.ProfessionalDevelopment'),
        ),
    ]
