# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0007_auto_20170721_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ZipCode',
            field=models.IntegerField(default=0, verbose_name='Zip Code'),
        ),
    ]
