# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0007_auto_20170622_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gpa',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='year_of_experience',
            field=models.CharField(max_length=200),
        ),
    ]
