# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0008_merge_20170712_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_company',
            name='EndDate',
            field=models.DateField(default=12, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='person_company',
            name='StartDate',
            field=models.DateField(default=12, verbose_name='Start Date'),
        ),
    ]
