# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0008_merge_20170712_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='operator',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person_company',
            name='EndDate',
            field=models.DateField(default=13, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='person_company',
            name='StartDate',
            field=models.DateField(default=13, verbose_name='Start Date'),
        ),
    ]
