# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0008_auto_20170623_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='year_of_experience',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
