# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0009_auto_20170712_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_company',
            name='EndDate',
            field=models.DateField(default=13, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='person_company',
            name='StartDate',
            field=models.DateField(default=13, verbose_name='Start Date'),
        ),
    ]
