# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0009_auto_20170724_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persontoschool',
            name='CourseID',
        ),
        migrations.AlterField(
            model_name='major',
            name='MajorMinor',
            field=models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], default='Major', max_length=50, verbose_name='Major/Minor'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=26, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=26, verbose_name='Start Date'),
        ),
    ]
