# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0009_auto_20170724_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=26, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=26, verbose_name='Start Date'),
        ),
    ]
