# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0010_auto_20170726_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteering',
            name='Volunteer',
            field=models.ManyToManyField(through='RSR.PersonToVolunteering', to='RSR.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='LastUpdated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=31, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=31, verbose_name='Start Date'),
        ),
    ]
