# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0011_auto_20170728_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='WorkAuthorization',
            field=models.CharField(choices=[('Citizenship', 'Citizenship'), ('Permanent Resident', 'Permanent Resident'), ('Visa', 'Visa')], default='Citizenship', max_length=20, verbose_name='Work Authorization'),
        ),
    ]
