# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0012_auto_20170705_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Language'),
        ),
    ]
