# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0013_auto_20170705_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='language',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
