# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0013_coursework_coursetake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursework',
            name='Coursetake',
        ),
        migrations.RemoveField(
            model_name='professionaldevelopment',
            name='ProfessionalExperience',
        ),
        migrations.RemoveField(
            model_name='school',
            name='Students',
        ),
        migrations.RemoveField(
            model_name='volunteering',
            name='Volunteer',
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=2, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=2, verbose_name='Start Date'),
        ),
    ]
