# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0014_auto_20170802_2018'),
        ('RSR', '0014_auto_20170802_1149'),
    ]

    operations = [
    ]
